version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_local:
